units:
  kx: cx
  ky: cy
  px: cx + 2
  py: cy + 2
  pinkysplay: 0
  ringsplay: 0
points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
        height: ky
        width: kx
      anchor:
        rotate: pinkysplay+ringsplay
        shift: [100, -100]
      columns:
        pinky:
          key.column_net: P14
        ring:
          key:
            splay: -pinkysplay
            origin: [-12, -19]
            stagger: 12
            column_net: P7
        middle:
          key:
            splay: -ringsplay
            stagger: 7
            column_net: P8
        index:
          key:
            stagger: -2
            column_net: P9
        inner:
          key:
            stagger: 0
            column_net: P16
      rows:
        bottom:
          row_net: P15
        home:
          row_net: P18
        top:
          row_net: P19
    thumbfan:
      key:
        height: ky
        width: kx
      anchor:
        ref: matrix_index_bottom
        shift: [0, -18]
      columns:
        outer:
        home:
          key.spread: 21.25
          key.splay: -10
          key.origin: [-11, 0]
        inner:
          key.spread: 21.25
          key.splay: -10
          key.stagger: py*0.3
          key.width: px*1.5
          key.origin: [-9.5, -9]
          key.rotate: 90
      rows:
        thumb:
#  rotate: -25
#  mirror:
#    ref: matrix_inner_top
#    distance: 60
outlines:
  caps:
    - what: rectangle
      where: true
      size: [kx, ky]
  capposts:
    - what: rectangle
      where: true
      size: [7, 3]
  printborder:
    - what: polygon
      operation: stack
      points:
      - ref: matrix_pinky_top
        shift: [-1-0.5kx,1+0.5ky]
      - ref: matrix_ring_top
        shift: [-0.5kx,1+0.5ky]
      - ref: matrix_middle_top
        shift: [-0.5kx,1+0.5ky]
      - ref: matrix_middle_top
        shift: [0.5kx,1+0.5ky]
      - ref: matrix_inner_top
        shift: [1+1.5px,2+0.5ky]
      - ref: matrix_inner_bottom
        shift: [1+1.5px,1+0.5ky]
      - ref: thumbfan_inner_thumb
        shift: [1+0.75kx,-1-0.5ky]
      - ref: thumbfan_inner_thumb
        shift: [-1-0.75kx,-1-0.5ky]
      - ref: thumbfan_outer_thumb
        shift: [-0.5kx,-1-0.5ky]
      - ref: matrix_pinky_bottom
        shift: [-1-0.5kx,-1-0.5ky]
  printableposts:
    - name: printborder
    - operation: subtract
      name: caps
    - operation: add
      name: capposts
pcbs:
  flippable:
    outlines:
      main:
        outline: printborder
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      viacol:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [0, -4]
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -7]
      promicro:
        what: promicro_pretty
        where:
          ref: matrix_inner_top
          shift: [1px,-0.5kx]
          rotate: -90
      # oled:
      #   what: oled
      #   where:
      #     ref: matrix_inner_bottom
      #     shift: [5+0.5px,-2+0.5ky]
      #     rotate: 90
      #   params:
      #     SDA: P2
      #     SCL: P3
      reset_f:
        what: button
        where:
          ref: matrix_inner_bottom
          shift: [15,-7]
        params:
          from: RST
          to: GND
          side: F
      reset_b:
        what: button
        where:
          ref: matrix_inner_bottom
          shift: [15,-7]
        params:
          from: RST
          to: GND
          side: B
      power_f:
        what: slider
        where:
          ref: matrix_inner_bottom
          shift: [33,-1]
          rotate: -65
        params:
          from: battvcc
          to: RAW
          side: F
      power_b:
        what: slider
        where:
          ref: matrix_inner_bottom
          shift: [33,-1]
          rotate: -65
        params:
          from: battvcc
          to: RAW
          side: B
      trrs:
        what: trrs
        where:
          ref: matrix_inner_bottom
          shift: [-2+1.5px,3]
          rotate: -90
        params:
          reverse: true
          symmetric: true
          A: RAW
          B: RAW
          C: GND
          D: P3
      batt_vcc:
        what: pad
        where:
          ref: matrix_inner_bottom
          shift: [13,0]
        params:
          width: 2
          height: 2
          front: true
          back: true
          net: battvcc
      batt_gnd:
        what: pad
        where:
          ref: matrix_inner_bottom
          shift: [17,0]
        params:
          width: 2
          height: 2
          front: true
          back: true
          net: GND
