units:
  kx: cx
  ky: cy
  px: cx + 2
  py: cy + 2
  pinkysplay: 10
points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
        height: ky
        width: kx
      anchor:
        rotate: pinkysplay
        shift: [100, -100]
      columns:
        pinky:
        ring:
          key.splay: -pinkysplay
          key.origin: [-12, -19]
          key.stagger: 12
        middle:
          key.stagger: 7
        index:
          key.stagger: -2
        inner:
          key.stagger: 0
      rows:
        bottom:
        home:
        top:
    thumbfan:
      key:
        height: ky
        width: kx
      anchor:
        ref: matrix_inner_bottom
        shift: [-15, -18]
      columns:
        outer:
        home:
          key.spread: 21.25
          key.splay: -10
          key.origin: [-11.75, -9]
        inner:
          key.spread: 21.25
          key.splay: -10
          key.stagger: py*0.3
          key.height: py*1.5
          key.origin: [-9.5, -9]
      rows:
        thumb:
  rotate: -25
#  mirror:
#    ref: matrix_inner_top
#    distance: 60
outlines:
  caps:
    - what: rectangle
      where: true
      size: [kx, ky]
  capposts:
    - what: rectangle
      where: true
      size: [7, 3]
  printborder:
    - what: polygon
      operation: stack
      points:
      - ref: matrix_pinky_top
        shift: [-1-0.5kx,1+0.5ky]
      - ref: matrix_ring_top
        shift: [-0.5kx,1+0.5ky]
      - ref: matrix_middle_top
        shift: [-0.5kx,1+0.5ky]
      - ref: matrix_middle_top
        shift: [0.5kx,1+0.5ky]
      - ref: matrix_inner_top
        shift: [1+1.5kx,1+0.5ky]
      - ref: matrix_inner_bottom
        shift: [1+1.5kx,1+0.5ky]
      - ref: thumbfan_inner_thumb
        shift: [1+0.5kx,1+0.75ky]
      - ref: thumbfan_inner_thumb
        shift: [1+0.5kx,-1-0.75ky]
      - ref: thumbfan_outer_thumb
        shift: [-0.5kx,-1-0.5ky]
      - ref: matrix_pinky_bottom
        shift: [-1-0.5kx,-1-0.5ky]
  printableposts:
    - name: printborder
    - operation: subtract
      name: caps
    - operation: add
      name: capposts
pcbs:
  flippable:
    outlines:
      main:
        outline: printborder
    footprints:
      choc:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          keycaps: true
          reverse: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
